/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StoryStyle = IDL.Record({
  'ambientMusic' : IDL.Text,
  'colorPalette' : IDL.Text,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'action' : IDL.Null,
  'happy' : IDL.Null,
  'romantic' : IDL.Null,
  'suspense' : IDL.Null,
  'mystery' : IDL.Null,
  'dramatic' : IDL.Null,
  'neutral' : IDL.Null,
});
export const Scene = IDL.Record({
  'duration' : IDL.Nat,
  'mood' : Mood,
  'text' : IDL.Text,
});
export const Story = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'scenes' : IDL.Vec(Scene),
  'createdAt' : IDL.Int,
  'style' : StoryStyle,
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStory' : IDL.Func([IDL.Text, IDL.Text, StoryStyle], [IDL.Nat], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'getAllPublicStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleStoryVisibility' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateStory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, StoryStyle, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StoryStyle = IDL.Record({
    'ambientMusic' : IDL.Text,
    'colorPalette' : IDL.Text,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'action' : IDL.Null,
    'happy' : IDL.Null,
    'romantic' : IDL.Null,
    'suspense' : IDL.Null,
    'mystery' : IDL.Null,
    'dramatic' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const Scene = IDL.Record({
    'duration' : IDL.Nat,
    'mood' : Mood,
    'text' : IDL.Text,
  });
  const Story = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'scenes' : IDL.Vec(Scene),
    'createdAt' : IDL.Int,
    'style' : StoryStyle,
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStory' : IDL.Func([IDL.Text, IDL.Text, StoryStyle], [IDL.Nat], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'getAllPublicStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStories' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleStoryVisibility' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateStory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, StoryStyle, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };