/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Mood = { 'sad' : null } |
  { 'action' : null } |
  { 'happy' : null } |
  { 'romantic' : null } |
  { 'suspense' : null } |
  { 'mystery' : null } |
  { 'dramatic' : null } |
  { 'neutral' : null };
export interface Scene { 'duration' : bigint, 'mood' : Mood, 'text' : string }
export interface Story {
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'scenes' : Array<Scene>,
  'createdAt' : bigint,
  'style' : StoryStyle,
  'isPublic' : boolean,
}
export interface StoryStyle { 'ambientMusic' : string, 'colorPalette' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStory' : ActorMethod<[string, string, StoryStyle], bigint>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'getAllPublicStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStory' : ActorMethod<[bigint], [] | [Story]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStories' : ActorMethod<[Principal], Array<Story>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleStoryVisibility' : ActorMethod<[bigint], boolean>,
  'updateStory' : ActorMethod<
    [bigint, string, string, StoryStyle, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];